server/djangoapp/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from . import views

app_name = 'djangoapp'
urlpatterns = [
    # route is a string contains a URL pattern
    # view refers to the view function
    # name the URL
    path(route='', view=views.get_dealerships, name='index'),
    path('dealer/<int:dealer_id>/', views.get_dealer_details, name='dealer_details'),
    path('dealer/<int:dealer_id>/review', views.add_review, name='add_review'),
    path(route='about/', view=views.about, name='about'),
    path(route='contact/', view=views.contact, name='contact'),
    path('registration/', views.registration_request, name='registration'),
    path('login/', views.login_request, name='login'),
    path('logout/', views.logout_request, name='logout'),
    path(route='', view=views.get_dealerships, name='index'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

server/djangobackend/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    path('admin/', admin.site.urls),
    path('djangoapp/', include('djangoapp.urls')),
] 
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

server/djangoapp/models.py
from django.db import models
from django.core import serializers
from django.utils.timezone import now
import uuid
import json

# Create your models here.

class CarMake(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=30)
    description = models.CharField(max_length=1000)

    def __str__(self):
        return "Name: " + self.name + "," + \
               "Description: " + self.description


class CarModel(models.Model):
# - Many-To-One relationship to Car Make model (One Car Make has many Car Models, using ForeignKey field)
    id = models.AutoField(primary_key=True)
    carMake = models.ForeignKey(CarMake, on_delete=models.CASCADE)
    name = models.CharField(max_length=30)
    dealerid = models.IntegerField(default=0)
    SEDAN = 'Sedan'
    SUV ='SUV'
    WAGON = 'WAGON'
    CHOICES = [
        (SEDAN, 'Sedan'),
        (SUV, 'SUV'),
        (WAGON, 'WAGON'),
    ]
    Type =models.CharField(max_length=30,choices=CHOICES)
    Year=models.DateField(null=True)
    def __str__(self):
        return "Car name: " + self.name  

class DealerReview:
    def __init__(self,dealership,name,purchase,review,purchase_date,car_make,car_model,car_year,sentiment,id):
        self.dealership=dealership
        self.name=name
        self.purchase=purchase
        self.review=review
        self.purchase_date=purchase_date
        self.car_make=car_make
        self.car_model=car_model
        self.car_year=car_year
        self.sentiment=sentiment
        self.id=id
    def __str__(self):
        return "name: " + self.name


# <HINT> Create a plain Python class to hold review data
class CarDealer:

    def __init__(self, address, city, full_name, id, lat, long, short_name, st, zip):
        # Dealer address
        self.address = address
        # Dealer city
        self.city = city
        # Dealer Full Name
        self.full_name = full_name
        # Dealer id
        self.id = id
        # Location lat
        self.lat = lat
        # Location long
        self.long = long
        # Dealer short name
        self.short_name = short_name
        # Dealer state
        self.st = st
        # Dealer zip
        self.zip = zip

    def __str__(self):
        return "Dealer name: " + self.full_name

server/djangoapp/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth.models import User
from django.shortcuts import get_object_or_404, render, redirect
from .models import CarModel
from .restapis import get_dealers_from_cf,get_dealer_reviews_from_cf,post_request
from django.contrib.auth import login, logout, authenticate
from django.contrib import messages
from datetime import datetime
from dateutil.parser import parse
from django.urls import reverse
import logging
import json

# Get an instance of a logger
logger = logging.getLogger(__name__)


# Create your views here.


# Create an `about` view to render a static about page
def about(request):
    context = {}
    if request.method == "GET":
        return render(request, 'djangoapp/aboutus.html', context)
# ...

# Create a `contact` view to return a static contact page
def contact(request):
    context = {}
    if request.method == "GET":
        return render(request, 'djangoapp/contactus.html', context)

# Create a `login_request` view to handle sign in request
def login_request(request):
    context = {}
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('psw')
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('djangoapp:index')
        else:
            context['message'] = "Invalid username or password."
            return render(request, 'djangoapp/login.html', context)
    else:
        return render(request, 'djangoapp/login.html', context)


# Create a `logout_request` view to handle sign out request
def logout_request(request):
    logout(request)
    return redirect('djangoapp:index')

# Create a `registration_request` view to handle sign up request
def registration_request(request):
    context = {}
    if request.method == 'GET':
        return render(request, 'djangoapp/registration.html', context)
    elif request.method == 'POST':
        # Check if user exists
        username = request.POST['username']
        password = request.POST['psw']
        first_name = request.POST['firstname']
        last_name = request.POST['lastname']
        user_exist = False
        try:
            User.objects.get(username=username)
            user_exist = True
        except:
            logger.error("New user")
        if not user_exist:
            user = User.objects.create_user(username=username, first_name=first_name, last_name=last_name,
                                            password=password)
            login(request, user)
            return redirect("djangoapp:index")
        else:
            context['message'] = "User already exists."
            return render(request, 'djangoapp/registration.html', context)

# Update the `get_dealerships` view to render the index page with a list of dealerships
def get_dealerships(request):
    context ={}
    if request.method == "GET":
        url = "https://service.eu.apiconnect.ibmcloud.com/gws/apigateway/api/7eed226c81af75dae086a851aa8986b232fbb65a5f0a0483731fc5046f29267e/api/dealership"
        # Get dealers from the URL
        dealerships = get_dealers_from_cf(url)
        # Concat all dealer's short name
        #dealer_names = ' '.join([dealer.short_name for dealer in dealerships])
        context["dealership_list"]=dealerships
        return render(request, 'djangoapp/index.html', context)


# Create a `get_dealer_details` view to render the reviews of a dealer
def get_dealer_details(request, dealer_id):
    context={}
    if request.method == "GET":
            # LOCAL url = "https://service.eu.apiconnect.ibmcloud.com/gws/apigateway/api/7eed226c81af75dae086a851aa8986b232fbb65a5f0a0483731fc5046f29267e/api/review"
            # LOCAL url_dealer = "https://service.eu.apiconnect.ibmcloud.com/gws/apigateway/api/7eed226c81af75dae086a851aa8986b232fbb65a5f0a0483731fc5046f29267e/api/dealership"
            url = "https://1da01ea5.eu-gb.apigw.appdomain.cloud/api/review"
            url_dealer = "https://1da01ea5.eu-gb.apigw.appdomain.cloud/api/dealership"

            # Get dealers from the URL
            dealerships = get_dealer_reviews_from_cf(str(url)+'?dealerId='+str(dealer_id))
            dealer_name = get_dealers_from_cf(url_dealer)
            # Concat all dealer's short name
            context['review_list']=dealerships
            context['dealer_id']=dealer_id
            context['dealer']=dealer_name[dealer_id-1]

            #review = ' '.join([dealer.review for dealer in dealerships])
            # Return a list of dealer short name
            return render(request, 'djangoapp/dealer_details.html', context)

# Create a `add_review` view to submit a review

def add_review(request, dealer_id):
    context = {}
    print("thanks"+str(dealer_id))
    if request.method == 'GET':
        # LOCAL url = 'https://service.eu.apiconnect.ibmcloud.com/gws/apigateway/api/7eed226c81af75dae086a851aa8986b232fbb65a5f0a0483731fc5046f29267e/api/dealership'
        url = "https://1da01ea5.eu-gb.apigw.appdomain.cloud/api/dealership"
        dealerships = get_dealers_from_cf(url, **({'id':dealer_id}))
        context['dealer'] = dealerships[dealer_id-1]
        context['cars'] = CarModel.objects.filter(dealerid=dealer_id)
        return render(request, 'djangoapp/add_review.html', context)
    elif request.method == 'POST':
        # LOCAL url = 'https://service.eu.apiconnect.ibmcloud.com/gws/apigateway/api/7eed226c81af75dae086a851aa8986b232fbb65a5f0a0483731fc5046f29267e/api/review'
        url = "https://1da01ea5.eu-gb.apigw.appdomain.cloud/api/review"
        dealer_reviews = get_dealer_reviews_from_cf(url)
        max_id = max([review.id for review in dealer_reviews], default=100)
        new_id = max_id + 1 if max_id >= 100 else max_id + 100
        date = datetime.now()
        date = date.strftime('%Y-%m-%d')
        print(request.POST)
        if 'purchasecheck' in request.POST:
            car=request.POST['car_details']
            car = car.split("-")
            car_make = car[0]
            car_model = car[1]
            car_year = parse(car[2])
            car_year=car_year.year
            print("purchase_date")
            print(request.POST.get('purchase_date'))

            json_payload = {
                'doc': {
                    'id': new_id,
                    'name': request.user.first_name+" "+request.user.last_name,
                    'review': request.POST['review_content'],
                    'purchase': True,
                    'purchase_date': request.POST.get('purchase_date'),
                    'dealership': dealer_id,
                    'car_make': car_make,
                    'car_model': car_model,
                    'car_year': car_year,
                    'review_time': date
                }
            }
        else:
            json_payload = {
                'doc': {
                    'id': new_id,
                    'name': request.user.get_full_name(),
                    'review': request.POST['review_content'],
                    'purchase': False,
                    'dealership': dealer_id,
                    'review_time': date
                   }
            }
        
        json_payload=json.dumps(json_payload)
        print("sending")
        print(json_payload)
        post_request(url, json_payload)
        
        return HttpResponseRedirect(reverse(viewname='djangoapp:dealer_details', args=(str(dealer_id),)))

server/djangoapp/templates/djangoapp/aboutus.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <title>Dealership Review</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link type="text/css" href="{% static 'djangoapp/signin.css' %}" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <link href="https://unpkg.com/bootstrap-table@1.18.2/dist/bootstrap-table.min.css" rel="stylesheet">
    <script src="https://unpkg.com/bootstrap-table@1.18.2/dist/bootstrap-table.min.js"></script>
    <script src="https://unpkg.com/bootstrap-table@1.18.2/dist/extensions/filter-control/bootstrap-table-filter-control.min.js"></script>
</head>

<body>
    <!-- Navigation bar -->
    <nav class="navbar navbar-expand-md navbar-dark  bg-dark"><!--fixed-top-->
        <div class="container-fluid">
            <div class="navbar-header">
              <a class="navbar-brand" href="{% url 'djangoapp:index' %}"><img src="https://img.icons8.com/plasticine/50/000000/car--v2.png" width="18%" height="18%" class="d-inline-block align-top" alt="">Car Dealership</a>
              <a class="navbar-brand" href="{% url 'djangoapp:about' %}">About Us</a>
              <a class="navbar-brand" href="{% url 'djangoapp:contact' %}">Contact Us</a>
            </div>
            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                <li>
                    <a type="button" class="btn btn-outline-success"  href="#">{{ user.first_name }}({{ user.username }})</a>
                    <a type="button" class="btn btn-outline-light"  href="{% url 'djangoapp:logout' %}">Logout</a>
                </li>
                {% else %}
                <li>
                    <form class="form-inline" action="{% url 'djangoapp:login' %}" method="post">
                        {% csrf_token %}
                        <div class="input-group">
                            <input type="text" class="form-control" placeholder="Username" name="username" >
                            <input type="password" class="form-control" placeholder="Password" name="psw" >
                        </div>
                            <button class="btn btn-dark" type="submit">Login</button>
                            <a type="button" class="btn btn-outline-success" href="{% url 'djangoapp:registration' %}">Sign Up</a>
                        
                    </form>
                </li>
                {% endif %}
            </ul>
        </div>
    </nav>


    <p class="mt-5 mb-3 text-muted text-center">© Welcome to Best Cars dealership, home to the best cars in North America. We sell domestic and imported cars at reasonable prices.</p>
    <div><img class="mb-4" src="/static{{MEDIA_URL}}//car/us.png" height="50%" style="position: absolute;
        bottom: 0px;
        left: 0px;
        right: 0px;
        margin: auto;">
    </div>

</body>


</html>

server/djangoapp/templates/djangoapp/add_review.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <title>Dealership Review</title>
    
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link type="text/css" href="{% static 'djangoapp/signin.css' %}" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <link href="https://unpkg.com/bootstrap-table@1.18.2/dist/bootstrap-table.min.css" rel="stylesheet">
    <script src="https://unpkg.com/bootstrap-table@1.18.2/dist/bootstrap-table.min.js"></script>
    <script src="https://unpkg.com/bootstrap-table@1.18.2/dist/extensions/filter-control/bootstrap-table-filter-control.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.0/moment.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.39.0/js/tempusdominus-bootstrap-4.min.js" integrity="sha512-k6/Bkb8Fxf/c1Tkyl39yJwcOZ1P4cRrJu77p83zJjN2Z55prbFHxPs9vN7q3l3+tSMGPDdoH51AEU8Vgo1cgAA==" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.39.0/css/tempusdominus-bootstrap-4.min.css" integrity="sha512-3JRrEUwaCkFUBLK1N8HehwQgu8e23jTH4np5NHOmQOobuC4ROQxFwFgBLTnhcnQRMs84muMh0PnnwXlPq5MGjg==" crossorigin="anonymous" />

</head>

<body>
    <!-- Navigation bar -->
    <nav class="navbar navbar-expand-md navbar-dark  bg-dark"><!--fixed-top-->
        <div class="container-fluid">
            <div class="navbar-header">
              <a class="navbar-brand" href="{% url 'djangoapp:index' %}"><img src="https://img.icons8.com/plasticine/50/000000/car--v2.png" width="18%" height="18%" class="d-inline-block align-top" alt="">Car Dealership</a>
              <a class="navbar-brand" href="{% url 'djangoapp:about' %}">About Us</a>
              <a class="navbar-brand" href="{% url 'djangoapp:contact' %}">Contact Us</a>
            </div>
            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                <li>
                    <a type="button" class="btn btn-outline-success"  href="#">{{ user.first_name }}({{ user.username }})</a>
                    <a type="button" class="btn btn-outline-light"  href="{% url 'djangoapp:logout' %}">Logout</a>
                </li>
                {% else %}
                <li>
                    <form class="form-inline" action="{% url 'djangoapp:login' %}" method="post">
                        {% csrf_token %}
                        <div class="input-group">
                            <input type="text" class="form-control" placeholder="Username" name="username" >
                            <input type="password" class="form-control" placeholder="Password" name="psw" >
                        </div>
                            <button class="btn btn-dark" type="submit">Login</button>
                            <a type="button" class="btn btn-outline-success" href="{% url 'djangoapp:registration' %}">Sign Up</a>
                        
                    </form>
                </li>
                {% endif %}
            </ul>
        </div>
    </nav>
    <!-- Bootstrap Stylize Registration form -->
    {% if user.is_authenticated %}
    <div class="center">
        <div class="container" > <!--Style root div with .container class -->
            <main class="form-signin">
                <h3 class="h3 mb-3 fw-normal">Add a Review about <br>{{ dealer.full_name }}</h3>
                <form action="{% url 'djangoapp:add_review' dealer.id %}" method="POST">
                {% csrf_token %}
                <div class=" form-floating mb-3">
                    <textarea id="review_content" name="review_content" class="md-textarea form-control" rows="5" required></textarea>
                    <label for="review_content">Enter the review content:</label>
                </div>

                <div class="form-check mb-3">
                    <input class="form-check-input" type="checkbox" value="purchasecheck" id="purchasecheck" name="purchasecheck" >
                    <label class="form-check-label" for="purchasecheck">
                        Made purchase from {{dealer.full_name}} ?
                    </label>
                </div>

                <div class="input-group mb-3">
                    <label class="input-group-text" for="car_details">Select car</label>
                    <select class="form-select" id="car_details" name="car_details">
                        {% for car in cars %}    
                        <option selected value="{{car.name}}-{{car.carMake.name}}-{{ car.Year }}">
                            {{car.name}}-{{car.carMake.name}}-{{ car.Year }}
                        </option>
                        {% endfor %}
                    </select>
                </div>
                
                <div class="input-group mb-3">
                    
                    
                        <div class="input-group date"  id="datetimepicker1" data-target-input="nearest">
                            <label class="input-group-text" for="car_details">Date of Purchase</label>
                            <input type="text" name="purchase_date" class="form-control datetimepicker-input" data-target="#datetimepicker1"/>
                            <div class="input-group-append" data-target="#datetimepicker1" data-toggle="datetimepicker">
                                <div class="input-group-text"><img src="https://img.icons8.com/material-outlined/24/000000/planner.png"/></div>
                            </div>
                        </div>
                    
                    <script type="text/javascript">
                        $(function () {
                            $('#datetimepicker1').datetimepicker();
                        });
                    </script>
                </div>
                
                <button class="btn btn-outline-primary" type="submit">Add Review</button>
                </form>
                 <!--Style button with .btn and .btn-primary class 
                <button class="btn btn-outline-primary" href="{% url 'djangoapp:registration' %}">Sign Up</a>-->
                


            </main>
        </div>
        <div><img class="mb-4" src="/static{{MEDIA_URL}}//car/car2.png" height="100%" width="100%" style="padding-right: 10%;">
        </div>

    </div>
    {% endif %}

   

<!----------------------->
</body>

<script type="text/javascript">
$('#kt_datetimepicker_1').datetimepicker();
</script>


</html>

server/djangoapp/templates/djangoapp/contactus.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <title>Dealership Review</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link type="text/css" href="{% static 'djangoapp/signin.css' %}" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <link href="https://unpkg.com/bootstrap-table@1.18.2/dist/bootstrap-table.min.css" rel="stylesheet">
    <script src="https://unpkg.com/bootstrap-table@1.18.2/dist/bootstrap-table.min.js"></script>
    <script src="https://unpkg.com/bootstrap-table@1.18.2/dist/extensions/filter-control/bootstrap-table-filter-control.min.js"></script>
</head>

<body>
    <!-- Navigation bar -->
    <nav class="navbar navbar-expand-md navbar-dark  bg-dark"><!--fixed-top-->
        <div class="container-fluid">
            <div class="navbar-header">
              <a class="navbar-brand" href="{% url 'djangoapp:index' %}"><img src="https://img.icons8.com/plasticine/50/000000/car--v2.png" width="18%" height="18%" class="d-inline-block align-top" alt="">Car Dealership</a>
              <a class="navbar-brand" href="{% url 'djangoapp:about' %}">About Us</a>
              <a class="navbar-brand" href="{% url 'djangoapp:contact' %}">Contact Us</a>
            </div>
            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                <li>
                    <a type="button" class="btn btn-outline-success"  href="#">{{ user.first_name }}({{ user.username }})</a>
                    <a type="button" class="btn btn-outline-light"  href="{% url 'djangoapp:logout' %}">Logout</a>
                </li>
                {% else %}
                <li>
                    <form class="form-inline" action="{% url 'djangoapp:login' %}" method="post">
                        {% csrf_token %}
                        <div class="input-group">
                            <input type="text" class="form-control" placeholder="Username" name="username" >
                            <input type="password" class="form-control" placeholder="Password" name="psw" >
                        </div>
                            <button class="btn btn-dark" type="submit">Login</button>
                            <a type="button" class="btn btn-outline-success" href="{% url 'djangoapp:registration' %}">Sign Up</a>
                        
                    </form>
                </li>
                {% endif %}
            </ul>
        </div>
    </nav>


    <p class="mt-5 mb-3 text-muted text-center">We would love to hear from you contact us<br>contactus@mail.com<br>©CarDealership</p>

    <div><img class="mb-4" src="/static{{MEDIA_URL}}//car/contact.png" height="50%" style="position: absolute;
        bottom: 0px;
        left: 0px;
        right: 0px;
        margin: auto;">
    </div>

</body>


</html>

server/djangoapp/templates/djangoapp/dealer_details.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <title>Dealership Review</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link type="text/css" href="{% static 'djangoapp/cards.css' %}" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <link href="https://unpkg.com/bootstrap-table@1.18.2/dist/bootstrap-table.min.css" rel="stylesheet">
    <script src="https://unpkg.com/bootstrap-table@1.18.2/dist/bootstrap-table.min.js"></script>
    <script src="https://unpkg.com/bootstrap-table@1.18.2/dist/extensions/filter-control/bootstrap-table-filter-control.min.js"></script>
</head>

<body>
    <!-- Navigation bar -->
    <nav class="navbar navbar-expand-md navbar-dark  bg-dark"><!--fixed-top-->
        <div class="container-fluid">
            <div class="navbar-header">
              <a class="navbar-brand" href="{% url 'djangoapp:index' %}"><img src="https://img.icons8.com/plasticine/50/000000/car--v2.png" width="18%" height="18%" class="d-inline-block align-top" alt="">Car Dealership</a>
              <a class="navbar-brand" href="{% url 'djangoapp:about' %}">About Us</a>
              <a class="navbar-brand" href="{% url 'djangoapp:contact' %}">Contact Us</a>
            </div>
            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                <li>
                    <a type="button" class="btn btn-outline-success"  href="#">{{ user.first_name }}({{ user.username }})</a>
                    <a type="button" class="btn btn-outline-light"  href="{% url 'djangoapp:logout' %}">Logout</a>
                </li>
                {% else %}
                <li>
                    <form class="form-inline" action="{% url 'djangoapp:login' %}" method="post">
                        {% csrf_token %}
                        <div class="input-group">
                            <input type="text" class="form-control" placeholder="Username" name="username" >
                            <input type="password" class="form-control" placeholder="Password" name="psw" >
                        </div>
                            <button class="btn btn-dark" type="submit">Login</button>
                            <a type="button" class="btn btn-outline-success" href="{% url 'djangoapp:registration' %}">Sign Up</a>
                        
                    </form>
                </li>
                {% endif %}
            </ul>
        </div>
    </nav>
    <!-- Page content -->


    <!-- temp content -->
    {% if user.is_authenticated %}
    <div class="container " style="margin-top:15px">
            <div class="card">
            <div class=" card-body">
                <img src="https://img.icons8.com/external-sbts2018-lineal-color-sbts2018/75/000000/external-customer-review-lean-thinking-sbts2018-lineal-color-sbts2018.png" style="padding-left: inherit;"/>
                <a href="{% url 'djangoapp:add_review' dealer_id %}" style="padding: inherit;font-size: x-large;" >Add a review for {{dealer.full_name }}</a>
            </div></div></div>
    {% endif %}
     <div class="container" style="margin-top:15px">

            <div class="row">
            {% for view in review_list %} 
            <div class="col-lg-4">
                <div class="card card-margin">
                    <div class="card-header no-border">
                        <h5 class="card-title" style="margin-top:10px">{{view.name}}</h5>
                    </div>
                    <div class="card-body pt-0">
                        <div class="widget-49">
                        <div class="widget-49-row">
                            <div class="widget-49-title-wrapper">
                                <div class="widget-49-date-{{view.sentiment}}">
                                    <span class="widget-49-img"><img class="card-img-left widget-49-img-data" src="/static{{MEDIA_URL}}//emoji/{{view.sentiment}}.png"></span>
                                </div>

                            </div>
                            <div class="widget-49-meeting-info">
                                <span class="widget-49-meeting-time">{{view.purchase_date}}</span>
                            </div>
                        </div>
                            
                            <ol class="widget-49-meeting-points">
                               <span>{{view.review}}</span>
                            </ol>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
    <!-- add review -->
    